apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-server 
spec:
  capacity:
    storage: 200G
  accessModes:
  - ReadWriteMany
  claimRef:
    namespace: default
    name: redis-server-claim
  nfs:
    path: /fs
    server: 10.28.105.226
