apiVersion: v1
kind: PersistentVolume
metadata:
  name: spark-data-jx 
spec:
  capacity:
    storage: 5G
  accessModes:
  - ReadWriteMany
  claimRef:
    namespace: default
    name: spark-data-claim
  nfs:
    path: /exports
    server: 10.44.4.210
